import React from "react";
import { CreatePostButton } from "../../components/CreatePostButton";

export interface PrivacyProps {}

export const Privacy: React.FC<PrivacyProps> = (props) => {
	return (
		<div style={{ textAlign: "left" }}>
			<h1>Privacy</h1>
			<p>Last updated: August 19, 2020</p>
			<p>
				This Privacy Policy describes Our policies and procedures on the
				collection, use and disclosure of Your information when You use
				the Service and tells You about Your privacy rights and how the
				law protects You.
			</p>
			<p>
				We use Your Personal data to provide and improve the Service. By
				using the Service, You agree to the collection and use of
				information in accordance with this Privacy Policy.
			</p>
			<h1>Interpretation and Definitions</h1>
			<h2>Interpretation</h2>
			<p>
				The words of which the initial letter is capitalized have
				meanings defined under the following conditions.
			</p>
			<p>
				The following definitions shall have the same meaning regardless
				of whether they appear in singular or in plural.
			</p>
			<h2>Definitions</h2>
			<p>
				<ul>
					<li>
						For the purposes of this Privacy Policy: You means the
						individual accessing or using the Service, or the
						company, or other legal entity on behalf of which such
						individual is accessing or using the Service, as
						applicable.
					</li>
					<li>
						Company (referred to as either "the Company", "We", "Us"
						or "Our" in this Agreement) refers to ieso.
					</li>
					<li>
						Affiliate means an entity that controls, is controlled
						by or is under common control with a party, where
						"control" means ownership of 50% or more of the shares,
						equity interest or other securities entitled to vote for
						election of directors or other managing authority.
					</li>
					<li>
						Account means a unique account created for You to access
						our Service or parts of our Service.
					</li>
					<li>
						Website refers to ieso, accessible from
						https://ieso.help
					</li>
					<li>Service refers to the Website.</li>
					<li>Country refers to: New York, United States</li>
					<li>
						Service Provider means any natural or legal person who
						processes the data on behalf of the Company. It refers
						to third-party companies or individuals employed by the
						Company to facilitate the Service, to provide the
						Service on behalf of the Company, to perform services
						related to the Service or to assist the Company in
						analyzing how the Service is used. Third-party Social
						Media Service refers to any website or any social
						network website through which a User can log in or
						create an account to use the Service.
					</li>
					<li>
						Personal Data is any information that relates to an
						identified or identifiable individual.
					</li>
					<li>
						Cookies are small files that are placed on Your
						computer, mobile device or any other device by a
						website, containing the details of Your browsing history
						on that website among its many uses.
					</li>
					<li>
						Device means any device that can access the Service such
						as a computer, a cellphone or a digital tablet.
					</li>
					<li>
						Usage Data refers to data collected automatically,
						either generated by the use of the Service or from the
						Service infrastructure itself (for example, the duration
						of a page visit).
					</li>
				</ul>
			</p>
			<h2>Collecting and Using Your Personal Data</h2>
			<h3>Types of Data Collected</h3>
			<h4>User Provided Data</h4>
			<p>
				Account Information: Your username may be publicly or privately
				displayed when you interact with the Service, such as when you
				write a post or reply to another user’s post. Accounts,
				postings, and other user contributed content will be heavily
				moderated for personally identifiable information. In the case
				where such identifiable information is found, all such
				information will be removed.
			</p>
			<h4>Tracking Technologies and Cookies</h4>
			<p>
				We use Cookies or other technologies in order to improve user
				experience of our service. Our websites will set local storage
				data that is essential for the website to operate correctly.
				These are as follows:
				<ul>
					<li>
						Token: this is a URL-safe JSON web token (JWT) designed
						to Your session after login with username and
						credentials.
					</li>
					<li>
						Username – this cookie is a text value that identifies
						unique visitors by their chosen username.
					</li>
				</ul>
			</p>
			<h3>Use of Your Personal Data</h3>
			<p>
				The Company may use Personal Data for the following purposes:
				<ul>
					<li>
						To provide and maintain our Service, including to
						monitor the usage of our Service.
					</li>
					<li>
						To manage Your Account: to manage Your registration as a
						user of the Service. The Personal Data You provide can
						give You access to different functionalities of the
						Service that are available to You as a registered user.
					</li>
					<li>
						To manage Your requests: To attend and manage Your
						requests to Us.
					</li>
				</ul>
			</p>
			<p>
				We may share your personal information in the following
				situations: With other users:
				<ul>
					<li>
						when You share personal information or otherwise
						interact in the public areas with other users, such
						information may be viewed by all users and may be
						publicly distributed outside.
					</li>
				</ul>
			</p>
			<h3>Retention of Your Personal Data</h3>
			<p>
				The Company will retain Your Personal Data only for as long as
				is necessary for the purposes set out in this Privacy Policy. We
				will retain and use Your Personal Data to the extent necessary
				to comply with our legal obligations (for example, if we are
				required to retain your data to comply with applicable laws),
				resolve disputes, and enforce our legal agreements and policies.
			</p>
			<p>
				The Company will also retain Usage Data for internal analysis
				purposes. Usage Data is generally retained for a shorter period
				of time, except when this data is used to strengthen the
				security or to improve the functionality of Our Service, or We
				are legally obligated to retain this data for longer time
				periods.
			</p>
			<h4>Transfer of Your Personal Data</h4>
			<p>
				Your information, including Personal Data, is processed at the
				Company's operating offices and in any other places where the
				parties involved in the processing are located. It means that
				this information may be transferred to — and maintained on —
				computers located outside of Your state, province, country or
				other governmental jurisdiction where the data protection laws
				may differ than those from Your jurisdiction.
			</p>
			<p>
				Your consent to this Privacy Policy followed by Your submission
				of such information represents Your agreement to that transfer.
			</p>
			<p>
				The Company will take all steps reasonably necessary to ensure
				that Your data is treated securely and in accordance with this
				Privacy Policy and no transfer of Your Personal Data will take
				place to an organization or a country unless there are adequate
				controls in place including the security of Your data and other
				personal information.
			</p>
			<h3>Disclosure of Your Personal Data</h3>
			<h4>Law enforcement</h4>
			<p>
				Under certain circumstances, the Company may be required to
				disclose Your Personal Data if required to do so by law or in
				response to valid requests by public authorities (e.g. a court
				or a government agency).
			</p>
			<h4>Other legal requirements</h4>
			<p>
				The Company may disclose Your Personal Data in the good faith
				belief that such action is necessary to:
				<ul>
					<li>Comply with a legal obligation</li>
					<li>
						Protect the personal safety of Users of the Service or
						the public
					</li>
					<li>Protect against legal liability</li>
				</ul>
			</p>
			<h4>Security of Your Personal Data</h4>
			<p>
				The security of Your Personal Data is important to Us, but
				remember that no method of transmission over the Internet, or
				method of electronic storage is 100% secure. While We strive to
				use commercially acceptable means to protect Your Personal Data,
				We cannot guarantee its absolute security.
			</p>
			<h3>Children's Privacy</h3>
			<p>
				Our Service does not address anyone under the age of 18. We do
				not knowingly collect personally identifiable information from
				anyone under the age of 18. If You are a parent or guardian and
				You are aware that Your child has provided Us with Personal
				Data, please contact Us. If We become aware that We have
				collected Personal Data from anyone under the age of 18 without
				verification of parental consent, We take steps to remove that
				information from Our servers.
			</p>
			<h3>Links to Other Websites</h3>
			<p>
				Our Service may contain links to other websites that are not
				operated by Us. If You click on a third party link, You will be
				directed to that third party's site. We strongly advise You to
				review the Privacy Policy of every site You visit.
			</p>
			<p>
				We have no control over and assume no responsibility for the
				content, privacy policies or practices of any third party sites
				or services.
			</p>
			<h3>Changes to this Privacy Policy</h3>
			<p>
				We may update our Privacy Policy from time to time. We will
				notify You of any changes by posting the new Privacy Policy on
				this page.
			</p>
			<p>
				We will let You know via email and/or a prominent notice on Our
				Service, prior to the change becoming effective and update the
				"Last updated" date at the top of this Privacy Policy.
			</p>
			<p>
				You are advised to review this Privacy Policy periodically for
				any changes. Changes to this Privacy Policy are effective when
				they are posted on this page.
			</p>
			<h3>Contact Us</h3>
			<p>
				If you have any questions about this Privacy Policy, You can
				contact us:
				<ul>
					<li>
						By visiting this page on our website:
						http://ieso.cs.columbia.edu/contact
					</li>
				</ul>
			</p>
			<CreatePostButton />
		</div>
	);
};
